name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
#   repository_dispatch:
#     types: 
#         - webhook
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: TEST Env
      run: echo "URL=Hello Hau" >> $GITHUB_ENV
    
    - name: TEST Env
      run: echo ${{ env.URL }}
#     - name: Test github event
#       run: echo ${{ github.event.client_payload.unit }}
      
      # Push to Tele
#     - name: QR
#       run: wget -O qr.png https://api.qrserver.com/v1/create-qr-code/?data=https://github.com/hautvfami/vhbuilder/releases/download/build_branch/app-dev-release.apk&size=150x150
#     - name: Push to Telegram
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.CHAT_ID }}
#         token: ${{ secrets.BOT_TOKEN }}
#         format: markdown
#         message: |
#           #Build success             
#           master - dev
#           [Install APK](https://github.com/hautvfami/vhbuilder/releases/download/build_branch/app-dev-release.apk)
#         photo: qr.png



#     - name: Push
#       run: |
#         echo 'URL=https://github.com/hautvfami/vhbuilder/releases/download/build-branch/app-dev-release.apk' >> $GITHUB_ENV
#         echo 'QR=https://api.qrserver.com/v1/create-qr-code/?data=https://github.com/hautvfami/vhbuilder/releases/download/build-branch/app-dev-release.apk&size=150x150)' >> $GITHUB_ENV
#         curl --location --request GET 'https://api.telegram.org/bot5096122698:AAHwz7aBTIy-dzAGex_EeUPJeBluXXeWbZY/sendMessage?chat_id=-656569490&parse_mode=markdown&text=build-branch dev%0D%0A%0D%0AApp apk is ready at link below%0D%0A${{env.URL}}%0D%0A%0D%0A[](${{env.QR}})'
